name: lint

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: install reviewdog
      run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s  v0.9.13
    - name: install lint tools
      run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
    - name: lint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go vet ./... | ./bin/reviewdog -f=checkstyle -name=textlint -reporter=github-pr-review
          golangci-lint ./... | ./bin/reviewdog -f=checkstyle -name=textlint -reporter=github-pr-review
